### ISSUE TITLE
Does it need nem_ed25519 installed

### ISSUE THREAD

**Issue by tongokongo** [namuyan/nem-python#4]
Hey, I was trying to test the library but getting error:

```
Traceback (most recent call last):
  File "basic.py", line 1, in <module>
    from nem_python.nem_connect import NemConnect
  File "/home/pi/Desktop/namuyan/nem-python/nem_python/nem_connect.py", line 15, in <module>
    from .transaction_reform import TransactionReform
  File "/home/pi/Desktop/namuyan/nem-python/nem_python/transaction_reform.py", line 5, in <module>
    from nem_ed25519.key import get_address
ImportError: No module named 'nem_ed25519'
```

Also while installing https://github.com/namuyan/nem-ed25519 I am getting the errors:

```
 In file included from src/gmpy2.c:426:0:
  src/gmpy.h:106:19: fatal error: gmp.h: No such file or directory
   #  include "gmp.h"
                     ^
  compilation terminated.
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
```

**Comment by namuyan** [comment]
Hello, do you read [the document](https://github.com/namuyan/nem-ed25519#install)?

**Comment by namuyan** [comment]
No comments, gaveup or solved.
